name: 'Deploy to Harmony App Gallery'
description: 'Uploads and releases apps to Harmony App Gallery.'
author: 'ACaiCat'
branding:
  icon: 'upload'
  color: 'red'
inputs:
  credentials:
    description: 'Huawei Service Account credentials (JSON)'
    required: true
  app-id:
    description: 'App Id'
    required: true
  file-path:
    description: 'file path to upload'
    required: true
  file-name:
    description: 'desired file name to upload'
    required: true
  chinese-mainland-flag:
    deprecation:
      "this parameter is required when the developer's registered region is not
      Mainland China."
    required: false
    default: 0
  submit:
    description: 'whether or not to submit automatically'
    required: false
    default: false
  test-submit:
    description: 'whether or not to create and submit a test version'
    required: false
    default: false
  test-type:
    description:
      'test type: 3 for HarmonyOS invite test, 4 for HarmonyOS public test'
    required: false
    default: '3'
  test-desc:
    description: 'test version description, max 50 characters'
    required: false
    default: ''
  onshelf-self-detect:
    description: 'whether to run on-shelf self check: 0 no, 1 yes'
    required: false
    default: '0'

runs:
  using: node24
  main: dist/index.js
